name: Publish

on:
  push:
    branches: ["main"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      - uses: ko-build/setup-ko@v0.6
      - run: ko build -B --platform=linux/amd64,linux/arm64 .
